//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blkEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductName {
            get {
                return ((string)(this["txtProductName"]));
            }
            set {
                this["txtProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cbxCategoryLevel1 {
            get {
                return ((int)(this["cbxCategoryLevel1"]));
            }
            set {
                this["cbxCategoryLevel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cbxCategoryLevel2 {
            get {
                return ((int)(this["cbxCategoryLevel2"]));
            }
            set {
                this["cbxCategoryLevel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cbxCategoryLevel3 {
            get {
                return ((int)(this["cbxCategoryLevel3"]));
            }
            set {
                this["cbxCategoryLevel3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductDetail {
            get {
                return ((string)(this["txtProductDetail"]));
            }
            set {
                this["txtProductDetail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductSpec {
            get {
                return ((string)(this["txtProductSpec"]));
            }
            set {
                this["txtProductSpec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dgvProductSpecTable {
            get {
                return ((string)(this["dgvProductSpecTable"]));
            }
            set {
                this["dgvProductSpecTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductNote {
            get {
                return ((string)(this["txtProductNote"]));
            }
            set {
                this["txtProductNote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductDownload {
            get {
                return ((string)(this["txtProductDownload"]));
            }
            set {
                this["txtProductDownload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductRelate {
            get {
                return ((string)(this["txtProductRelate"]));
            }
            set {
                this["txtProductRelate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtGuaranteeNone {
            get {
                return ((bool)(this["rbtGuaranteeNone"]));
            }
            set {
                this["rbtGuaranteeNone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtGuaranteeSupport {
            get {
                return ((bool)(this["rbtGuaranteeSupport"]));
            }
            set {
                this["rbtGuaranteeSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtGuarantee6Month {
            get {
                return ((bool)(this["rbtGuarantee6Month"]));
            }
            set {
                this["rbtGuarantee6Month"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtGuarantee12Month {
            get {
                return ((bool)(this["rbtGuarantee12Month"]));
            }
            set {
                this["rbtGuarantee12Month"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkGuaranteeDiamond {
            get {
                return ((bool)(this["chkGuaranteeDiamond"]));
            }
            set {
                this["chkGuaranteeDiamond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductKeyword {
            get {
                return ((string)(this["txtProductKeyword"]));
            }
            set {
                this["txtProductKeyword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductPicture {
            get {
                return ((string)(this["txtProductPicture"]));
            }
            set {
                this["txtProductPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtProductVideo {
            get {
                return ((string)(this["txtProductVideo"]));
            }
            set {
                this["txtProductVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkUserName {
            get {
                return ((bool)(this["chkUserName"]));
            }
            set {
                this["chkUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtUserName {
            get {
                return ((string)(this["txtUserName"]));
            }
            set {
                this["txtUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkUserDate {
            get {
                return ((bool)(this["chkUserDate"]));
            }
            set {
                this["chkUserDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int style {
            get {
                return ((int)(this["style"]));
            }
            set {
                this["style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkGetImageProfile {
            get {
                return ((bool)(this["chkGetImageProfile"]));
            }
            set {
                this["chkGetImageProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAddToListImage {
            get {
                return ((bool)(this["chkAddToListImage"]));
            }
            set {
                this["chkAddToListImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cbxFileDriveListOrderBy {
            get {
                return ((int)(this["cbxFileDriveListOrderBy"]));
            }
            set {
                this["cbxFileDriveListOrderBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lbxProductNameRequestList {
            get {
                return ((int)(this["lbxProductNameRequestList"]));
            }
            set {
                this["lbxProductNameRequestList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lbxProductNameDoneList {
            get {
                return ((int)(this["lbxProductNameDoneList"]));
            }
            set {
                this["lbxProductNameDoneList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtAddHtmlToDescription {
            get {
                return ((bool)(this["rbtAddHtmlToDescription"]));
            }
            set {
                this["rbtAddHtmlToDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtAddHtmlToContent {
            get {
                return ((bool)(this["rbtAddHtmlToContent"]));
            }
            set {
                this["rbtAddHtmlToContent"] = value;
            }
        }
    }
}
